SELECT 
 
  ii.unique_invoice_item_id,
  ii.unique_invoice_id,
  ii.unique_sales_order_id,
  ii.sales_order_number,
  ii.invoice_number,
  ii.sku,
  ii.item_name,
  ii.item_type,
  ii.quantity,
  ii.quantity_ordered,
  ii.quantity_backordered,
  ii.unit_price,
  ii.extension,
  ii.header_number,
  ii.line_number,
  ii.transaction_date, 
  ii.invoice_date,
  ii.customer_code,
  ii.bill_to_name,
  ii.invoice_type,
  ii.invoice,
  ii.ship_date,
  ii.ship_to_name,
  ii.ship_to_address1,
  ii.ship_to_address2,
  ii.ship_to_address3,
  ii.ship_to_city,
  ii.ship_to_state,
  ii.ship_to_zip,
  ii.ship_to_country,
  ii.invoice_sales_tax,
  ii.invoice_freight,
  ii.comment,
  ii.total_weight,
  ii.account_invoice_number,
  ii.created_at,
  ii.created_by,
  ii.updated_at,
  ii.updated_by,
  i.account_paid_coffee_invoice_number,
  ii.warehouse_name,
  ii.invoice_warehouse_name
  
  from {{ref('warehouse_base_invoice_items')}} ii
  join {{ref('warehouse_invoices')}} i on i.unique_invoice_id = ii.unique_invoice_id