select 

	so.sales_order_number, 
	line_number,
	order_date, 
	order_type,
	ship_date,
	nvl(rrdd.revised_requested_delivery_date,requested_delivery_date) as requested_delivery_date,
	customer_code,
	customer_purchase_order_number,
	ship_to_code,
	ship_to_name,
	ship_to_address,
	ship_to_city,
	ship_to_state,
	ship_to_zip,
	ship_via,
	warehouse,
	invoice_number,
	sku,
	item_name,
  kit_type,
	price_level,
	quantity_ordered,
	quantity_original,
	extension,
	weight,
	unit_price,
	created_at,
	created_by,
	updated_at,
	updated_by,
	order_comment,
	gl_account_key

from {{ref('so_sales_orders')}} so
left join {{ref('revised_requested_delivery_date')}} rrdd on so.sales_order_number = rrdd.sales_order_number
