select
unique_sales_order_id,
sales_order_number,
order_date,
order_status,
customer_code,
web_order_number,
bill_to_name,
bill_to_address,
bill_to_city,
bill_to_state,
bill_to_zip,
bill_to_country,
ship_to_name,
ship_to_address,
ship_to_city,
ship_to_state,
ship_to_zip,
ship_to_country,
customer_purchase_order_number,
email_address,
order_subtotal,
sales_tax,
freight,
created_at,
created_by,
updated_at,
updated_by,
rank() over (partition by customer_code order by order_date, sales_order_number ASC) AS account_order_number

from {{ref('sales_order_history_header')}}