version: 2

sources:
  - name: lambda_uploads
    loader: lambda

    tables:

    - name: wholesale_revised_rdd
      description: Manual override for requested delivery date. In cases where Tremaine provides a revised RDD for a sales_order_number, this will automatically flow through to all reports in place of the requested_delivery_date. Google Sheet accessible here - https://docs.google.com/spreadsheets/d/1FzyFf-_hSYqSshLnSpHpz2TyuwxhbsXuWyULBbS14dg/edit#gid=0


models:

  - name: warehouse_invoices
    columns:
      - name: unique_invoice_id
        description: Unique identifier at the invoice level. MD5 hash of the schema name (lcg, lch, or lct) || invoiceno || headerseqno from ar_invoice_history_header
        tests: 
          - not_null:
              tags: wholesale_tests
          - unique:
              tags: wholesale_tests